#!/bin/bash
# Batch 2 — 113 additional leagues

cd "/Users/julesmathis/NinjaScores APP"

run() {
  local id=$1 slug=$2 name=$3
  echo ""
  echo "=========================================="
  echo "▶  $name (ID: $id)"
  echo "=========================================="
  python3 scrape_premier_league.py --league "$id" --slug "$slug" --name "$name"
  echo "✓  Done: $name"
}

# Africa / Middle East
run 537  "premier-soccer-league"      "Premier Soccer League"
run 516  "ligue-1-algerie"            "Ligue 1 Algerie"
run 530  "botola-pro"                 "Botola Pro"   # already done — skip if file exists? handled below
run 533  "professional-football-league" "Professional Football League Nigeria"
run 519  "premier-league-egypte"      "Premier League Egypte"
run 522  "premier-league-ghana"       "Premier League Ghana"
run 524  "stars-league"               "Stars League Irak"
run 523  "persian-gulf"               "Persian Gulf Iran"
run 9372 "azadegan-league"            "Azadegan League Iran"
run 529  "premier-league-koweit"      "Premier League Koweit"
run 535  "qatar-stars-league"         "Qatar Stars League"
run 536  "saudi-pro-league"           "Saudi Pro League"   # already in batch1
run 538  "pro-league-emirats"         "Pro League Emirats"
run 544  "ligue-1-tunisie"            "Ligue 1 Tunisie"
run 9066 "premier-league-tanzanie"    "Premier League Tanzanie"

# Europe — West
run 260  "kategoria-superiore"        "Kategoria Superiore"
run 118  "premier-league-armenie"     "Premier League Armenie"
run 119  "2-liga-autriche"            "2. Liga Autriche"
run 262  "premier-league-azerbaidjan" "Premier League Azerbaidjan"
run 264  "first-division-b"           "First Division B Belgique"
run 270  "first-professional-league"  "First Professional League Bulgarie"
run 9096 "second-professional-league" "Second Professional League Bulgarie"
run 9986 "premier-league-canada"      "Premier League Canada"
run 9837 "canadian-championship"      "Canadian Championship"
run 136  "1-division-chypre"          "1. Division Chypre"
run 9100 "2-division-chypre"          "2. Division Chypre"
run 252  "hnl"                        "HNL Croatie"
run 85   "1-division-danemark"        "1. Division Danemark"
run 123  "championship-ecosse"        "Championship Ecosse"
run 8968 "primera-federacion"         "Primera Federacion Espagne"
run 248  "premium-liiga"              "Premium liiga Estonie"
run 8970 "ligue-3"                    "Ligue 3 France"
run 9677 "premiere-ligue-feminine"    "Premiere Ligue Feminine France"
run 439  "erovnuli-liga"              "Erovnuli Liga Georgie"
run 135  "super-league-1"             "Super League 1 Grece"
run 8815 "super-league-2"             "Super League 2 Grece"
run 212  "nb-i"                       "NB I Hongrie"
run 9117 "nb-ii"                      "NB II Hongrie"
run 250  "premier-league-feroe"       "Premier League Iles Feroe"
run 126  "premier-division-irlande"   "Premier Division Irlande"
run 218  "first-division-irlande"     "First Division Irlande"
run 129  "premiership-irlande-nord"   "Premiership Irlande du Nord"
run 215  "besta-deildin"              "Besta deildin Islande"
run 216  "1-deild"                    "1. Deild Islande"
run 127  "ligat-haal"                 "Ligat haAl Israel"
run 128  "leumit-league"              "Leumit League Israel"
run 86   "serie-b-italie"             "Serie B Italie"
run 147  "serie-c"                    "Serie C Italie"
run 10178 "serie-a-femminile"         "Serie A Femminile Italie"
run 225  "premier-league-kazakhstan"  "Premier League Kazakhstan"
run 226  "virsliga"                   "Virsliga Lettonie"
run 228  "a-lyga"                     "A Lyga Lituanie"
run 229  "national-division-luxembourg" "National Division Luxembourg"
run 249  "prva-liga-macedoine"        "Prva Liga Macedoine du Nord"
run 231  "national-division-moldavie" "National Division Moldavie"
run 232  "1-cfl-montenegro"           "1. CFL Montenegro"
run 59   "eliteserien"                "Eliteserien Norvege"
run 203  "1-divisjon"                 "1. Divisjon Norvege"
run 116  "cymru-premier"              "Cymru Premier Pays de Galles"
run 57   "eredivisie"                 "Eredivisie Pays-Bas"
run 111  "eerste-divisie"             "Eerste Divisie Pays-Bas"
run 196  "ekstraklasa"                "Ekstraklasa Pologne"
run 197  "i-liga-pologne"             "I Liga Pologne"
run 185  "liga-portugal-2"            "Liga Portugal 2"
run 189  "liga-i-roumanie"            "Liga I Roumanie"
run 9113 "liga-ii-roumanie"           "Liga II Roumanie"
run 63   "premier-league-russie"      "Premier League Russie"
run 338  "1-division-russie"          "1. Division Russie"
run 182  "super-liga-serbie"          "Super Liga Serbie"
run 176  "1-liga-slovaquie"           "1. liga Slovaquie"
run 8973 "2-liga-slovaquie"           "2. liga Slovaquie"
run 173  "prva-liga-slovenie"         "Prva Liga Slovenie"
run 67   "allsvenskan"                "Allsvenskan Suede"
run 168  "superettan"                 "Superettan Suede"
run 69   "super-league-suisse"        "Super League Suisse"
run 163  "challenge-league"           "Challenge League Suisse"
run 122  "1-liga-tcheque"             "1. Liga Tcheque"
run 253  "fnl-tcheque"                "FNL Tcheque"
run 165  "1-lig-turquie"              "1. Lig Turquie"
run 441  "premier-league-ukraine"     "Premier League Ukraine"

# Americas
run 112  "liga-profesional"           "Liga Profesional Argentine"
run 263  "premier-league-bielorussie" "Premier League Bielorussie"
run 144  "primera-division-bolivie"   "Primera Division Bolivie"
run 8814 "serie-b-bresil"             "Serie B Brasil"
run 273  "liga-de-primera"            "Liga de Primera Chili"
run 274  "primera-a-colombie"         "Primera A Colombie"
run 9125 "primera-b-colombie"         "Primera B Colombie"
run 121  "primera-division-costa-rica" "Primera Division Costa Rica"
run 336  "liga-nacional-guatemala"    "Liga Nacional Guatemala"
run 337  "liga-nacional-honduras"     "Liga Nacional Honduras"
run 130  "mls"                        "MLS"   # already in batch1
run 9039 "lpf-panama"                 "LPF Panama"
run 199  "division-profesional-paraguay" "Division Profesional Paraguay"
run 131  "liga-1-perou"               "Liga 1 Perou"
run 335  "primera-division-salvador"  "Primera Division Salvador"
run 161  "primera-division-uruguay"   "Primera Division Uruguay"
run 9122 "segunda-division-uruguay"   "Segunda Division Uruguay"
run 339  "primera-division-venezuela" "Primera Division Venezuela"
run 267  "premier-league-bosnie"      "Premier League Bosnie"

# Asia / Oceania
run 10433 "bangladesh-football-league" "Bangladesh Football League"
run 9080 "k-league-1"                 "K League 1 Coree du Sud"
run 9116 "k-league-2"                 "K League 2 Coree du Sud"
run 9537 "k-league-3"                 "K League 3 Coree du Sud"
run 120  "super-league-chine"         "Super League Chine"   # already in batch1
run 113  "a-league"                   "A-League Australie"
run 9478 "indian-super-league"        "Indian Super League Inde"
run 8982 "indian-football-league"     "Indian Football League Inde"
run 8983 "super-league-indonesie"     "Super League Indonesie"
run 223  "j-league"                   "J.League Japon"   # already in batch1
run 8974 "j-league-2"                 "J. League 2 Japon"
run 9136 "j-league-3"                 "J. League 3 Japon"
run 461  "premier-league-singapour"   "Premier League Singapour"
run 8984 "thai-league"                "Thai League Thailande"
run 9498 "thai-league-2"              "Thai League 2 Thailande"
run 9088 "v-league"                   "V-League Vietnam"
run 8985 "liga-super-malaisie"        "Liga Super Malaisie"
run 8870 "championship-nz"            "Championship NZ"
run 540  "superliga-ouzbekistan"      "Superliga Ouzbekistan"

echo ""
echo "=========================================="
echo "✅  BATCH 2 COMPLETE"
ls -lh *_database.csv | wc -l
echo " CSV files generated"
echo "=========================================="
