// Correspondance nom francais affiche dans NinjaScores -> nom pays API-Football.
// Etabli en confrontant notre liste a /countries : tout nom non resolu est
// signale, jamais deviné en silence.
module.exports = {
  'Afrique du Sud':'South-Africa','Albanie':'Albania','Algérie':'Algeria',
  'Allemagne':'Germany','Andorre':'Andorra','Angleterre':'England','Angola':'Angola',
  'Arabie saoudite':'Saudi-Arabia','Argentine':'Argentina','Arménie':'Armenia',
  'Australie':'Australia','Autriche':'Austria','Azerbaïdjan':'Azerbaijan',
  'Bahreïn':'Bahrain','Bangladesh':'Bangladesh','Belgique':'Belgium','Bénin':'Benin',
  'Biélorussie':'Belarus','Bolivie':'Bolivia','Bosnie-Herzégovine':'Bosnia',
  'Botswana':'Botswana','Brésil':'Brazil','Brunei':'Brunei','Bulgarie':'Bulgaria',
  'Burkina Faso':'Burkina-Faso','Burundi':'Burundi','Cambodge':'Cambodia',
  'Cameroun':'Cameroon','Canada':'Canada','Cap-Vert':'Cape-Verde','Chili':'Chile',
  'Chine':'China','Chypre':'Cyprus','Colombie':'Colombia','Congo':'Congo',
  'Corée du Sud':'South-Korea','Costa Rica':'Costa-Rica',"Côte d'Ivoire":'Ivory-Coast',
  'Croatie':'Croatia','Curaçao':'Curacao','Danemark':'Denmark','Écosse':'Scotland',
  'Égypte':'Egypt','Émirats arabes unis':'United-Arab-Emirates','Équateur':'Ecuador',
  'Espagne':'Spain','Estonie':'Estonia','États-Unis':'USA','Éthiopie':'Ethiopia',
  'Fidji':'Fiji','Finlande':'Finland','France':'France','Gabon':'Gabon',
  'Gambie':'Gambia','Géorgie':'Georgia','Ghana':'Ghana','Gibraltar':'Gibraltar',
  'Grèce':'Greece','Guatemala':'Guatemala','Guinée':'Guinea',
  'Guinée équatoriale':'Equatorial-Guinea','Haïti':'Haiti','Honduras':'Honduras',
  'Hong Kong':'Hong-Kong','Hongrie':'Hungary','Îles Féroé':'Faroe-Islands',
  'Îles Salomon':'Solomon-Islands','Inde':'India','Indonésie':'Indonesia',
  'Irak':'Iraq','Iran':'Iran','Irlande':'Ireland','Irlande du Nord':'Northern-Ireland',
  'Islande':'Iceland','Israël':'Israel','Italie':'Italy','Jamaïque':'Jamaica',
  'Japon':'Japan','Jordanie':'Jordan','Kazakhstan':'Kazakhstan','Kenya':'Kenya',
  'Kirghizistan':'Kyrgyzstan','Kosovo':'Kosovo','Koweït':'Kuwait','Laos':'Laos',
  'Lettonie':'Latvia','Liban':'Lebanon','Liberia':'Liberia','Libye':'Libya',
  'Lituanie':'Lithuania','Luxembourg':'Luxembourg','Macédoine du Nord':'Macedonia',
  'Madagascar':'Madagascar','Malaisie':'Malaysia','Malawi':'Malawi',
  'Maldives':'Maldives','Mali':'Mali','Malte':'Malta','Maroc':'Morocco',
  'Mauritanie':'Mauritania','Mexique':'Mexico','Moldavie':'Moldova',
  'Mongolie':'Mongolia','Monténégro':'Montenegro','Mozambique':'Mozambique',
  'Myanmar':'Myanmar','Namibie':'Namibia','Népal':'Nepal','Niger':'Niger',
  'Nigéria':'Nigeria','Norvège':'Norway','Nouvelle-Zélande':'New-Zealand',
  'Oman':'Oman','Ouganda':'Uganda','Ouzbékistan':'Uzbekistan','Pakistan':'Pakistan',
  'Palestine':'Palestine','Panama':'Panama',
  'Papouasie-Nouvelle-Guinée':'Papua-New-Guinea','Paraguay':'Paraguay',
  'Pays de Galles':'Wales','Pays-Bas':'Netherlands','Pérou':'Peru',
  'Philippines':'Philippines','Pologne':'Poland','Portugal':'Portugal','Qatar':'Qatar',
  'RD Congo':'Congo-DR','République tchèque':'Czech-Republic','Roumanie':'Romania',
  'Russie':'Russia','Rwanda':'Rwanda','Saint-Marin':'San-Marino',
  'Salvador':'El-Salvador','Sénégal':'Senegal','Serbie':'Serbia',
  'Sierra Leone':'Sierra-Leone','Singapour':'Singapore','Slovaquie':'Slovakia',
  'Slovénie':'Slovenia','Somalie':'Somalia','Soudan':'Sudan','Sri Lanka':'Sri-Lanka',
  'Suède':'Sweden','Suisse':'Switzerland','Suriname':'Suriname','Syrie':'Syria',
  'Tadjikistan':'Tajikistan','Tahiti':'Tahiti','Taïwan':'Taiwan',
  'Tanzanie':'Tanzania','Tchad':'Chad','Thaïlande':'Thailand','Togo':'Togo',
  'Trinité-et-Tobago':'Trinidad-And-Tobago','Tunisie':'Tunisia',
  'Turkménistan':'Turkmenistan','Turquie':'Turkey','Ukraine':'Ukraine',
  'Uruguay':'Uruguay','Vanuatu':'Vanuatu','Venezuela':'Venezuela','Viêt Nam':'Vietnam',
  'Yémen':'Yemen','Zambie':'Zambia','Zimbabwe':'Zimbabwe',
};
